export class PaperReveal {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.source=document.createElement('canvas');this.source.width=768;this.source.height=768;this.mask=document.createElement('canvas');this.mask.width=768;this.mask.height=768;this.mc=this.mask.getContext('2d',{willReadFrequently:true});this.layer=document.createElement('canvas');this.layer.width=768;this.layer.height=768;this.lc=this.layer.getContext('2d');this.target=null;this.ready=false;this.preview=false;this.completion=0;}
 async load(){const img=new Image();img.src='../../outputs/assets/ink_reference_painting.png';await img.decode();this.source.height=Math.round(this.source.width*img.naturalHeight/img.naturalWidth);this.mask.height=this.layer.height=this.source.height;this.source.getContext('2d').drawImage(img,0,0,this.source.width,this.source.height);const data=this.source.getContext('2d').getImageData(0,0,this.source.width,this.source.height).data;this.target=new Float32Array(data.length/4);this.total=0;for(let i=0;i<this.target.length;i++){const l=(data[i*4]+data[i*4+1]+data[i*4+2])/3;const weight=Math.max(0,(225-l)/225);this.target[i]=weight;this.total+=weight;}this.ready=true;this.resize();}
 resize(){const b=this.canvas.getBoundingClientRect();this.w=b.width;this.h=b.height;const d=Math.min(devicePixelRatio,2);this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);const s=Math.min(this.w*.90/this.source.width,this.h*.90/this.source.height);this.rect={x:(this.w-this.source.width*s)/2,y:(this.h-this.source.height*s)/2,w:this.source.width*s,h:this.source.height*s};}
 reset(){this.mc.clearRect(0,0,this.mask.width,this.mask.height);this.completion=0;this.preview=false;}
 absorb(fluid){if(!this.ready)return;const r=this.rect,sx=fluid.width/this.w,sy=fluid.height/this.h;this.mc.save();this.mc.globalAlpha=.55;this.mc.drawImage(fluid,r.x*sx,r.y*sy,r.w*sx,r.h*sy,0,0,this.mask.width,this.mask.height);this.mc.restore();const data=this.mc.getImageData(0,0,this.mask.width,this.mask.height).data;let sum=0;for(let i=0;i<this.target.length;i++)sum+=this.target[i]*data[i*4+3]/255;this.completion=this.total?sum/this.total:0;}
 draw(){const c=this.ctx;c.clearRect(0,0,this.w,this.h);if(!this.ready)return;const r=this.rect;c.save();c.globalCompositeOperation='multiply';if(this.preview){c.globalAlpha=.25;c.drawImage(this.source,r.x,r.y,r.w,r.h);}this.lc.clearRect(0,0,this.layer.width,this.layer.height);this.lc.globalCompositeOperation='source-over';this.lc.drawImage(this.source,0,0);this.lc.globalCompositeOperation='destination-in';this.lc.drawImage(this.mask,0,0);c.globalAlpha=1;c.drawImage(this.layer,r.x,r.y,r.w,r.h);c.restore();c.strokeStyle='rgba(95,89,70,.12)';c.strokeRect(r.x,r.y,r.w,r.h);}
}

